version: "2.1"
services:
  mongo:
    image: mongo:3.6.8
    ports:
      - "27017:27017"
    command: --smallfiles



  mongo-client:
    image: mongoclient/mongoclient
    ports:
      - "3030:3000"
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo

  # APP  ***************************************************************************************
  kotlin-spring-restful-api:
    image: kotlin-spring-restful-api
    ports:
      - "9090:8080"
    links:
      - mongo
